# Site settings
title: LightBulbOne
email: info@lightbulbone.com
description: > # this means to ignore newlines until "baseurl:"
  One bright idea after another.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.lightbulbone.com" # the base hostname & protocol for your site
twitter_username: lightbulbone
github_username:  lightbulbone

# Build settings
markdown: kramdown

sass:
  sass_dir: bower_components
  style: compressed
